#!/usr/bin/env python3
"""
RoadScan -- train a pothole/crack detector and export it for on-device use.

    python train_export.py prepare --rdd2022 /path/to/RDD2022
    python train_export.py train   --epochs 100
    python train_export.py export
    python train_export.py verify

Why LiteRT and not TFLite
-------------------------
Ultralytics REMOVED the standalone `tflite` export format in 8.4.83. The
replacement is `format="litert"`, which emits the same .tflite file -- LiteRT
is simply Google's current name for the TensorFlow Lite runtime. Passing
format="tflite" to a current Ultralytics will not work.

Class contract with the app
---------------------------
The Flutter side (lib/models/detection.dart) maps model class NAMES onto its
two hazard classes by substring, so the names baked into the export matter:
anything containing "pothole" becomes a pothole, anything containing "crack"
(or "alligator"/"crazing") becomes a crack. `verify` checks this holds.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATASET_DIR = HERE / "dataset"
DATA_YAML = DATASET_DIR / "roadscan.yaml"
RUNS_DIR = HERE / "runs"
ASSET_DIR = HERE.parent / "assets" / "models"
ASSET_NAME = "roadscan.tflite"

# Order defines the class indices written into the export. Keep it stable --
# changing it silently invalidates every previously trained weight file.
CLASSES = ["pothole", "crack"]

# RDD2022 (Road Damage Detection 2022) is the best public starting point: it is
# multi-country and INCLUDES an India split, which matters because the damage
# morphology and road construction in the RDD India images are far closer to
# Bidholi than the Japan/Czech splits are.
#
#   D00 longitudinal crack
#   D10 transverse crack
#   D20 alligator crack
#   D40 pothole
#
# D43/D44 are markings and crosswalk blur -- not road damage, so dropped.
RDD_MAP = {"D00": "crack", "D10": "crack", "D20": "crack", "D40": "pothole"}


def _require_ultralytics():
    try:
        from ultralytics import YOLO  # noqa: F401
    except ImportError:
        sys.exit(
            "ultralytics is not installed.\n"
            "  pip install -r ml/requirements.txt"
        )


# ---------------------------------------------------------------------------
# prepare
# ---------------------------------------------------------------------------

def cmd_prepare(args: argparse.Namespace) -> None:
    """Writes the dataset YAML, and optionally remaps an RDD2022 export."""
    for split in ("train", "val"):
        (DATASET_DIR / "images" / split).mkdir(parents=True, exist_ok=True)
        (DATASET_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)

    DATA_YAML.write_text(
        "# Generated by ml/train_export.py -- do not hand-edit class order.\n"
        f"path: {DATASET_DIR.as_posix()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n"
        + "".join(f"  {i}: {name}\n" for i, name in enumerate(CLASSES)),
        encoding="utf-8",
    )
    print(f"wrote {DATA_YAML}")

    if args.rdd2022:
        _remap_rdd(Path(args.rdd2022))

    n_train = len(list((DATASET_DIR / "images" / "train").glob("*")))
    n_val = len(list((DATASET_DIR / "images" / "val").glob("*")))
    print(f"train images: {n_train}   val images: {n_val}")

    if n_train == 0:
        print(
            "\nNo training images yet. Two options, best used together:\n"
            "  1. Download RDD2022 and re-run with --rdd2022 <dir> for a base.\n"
            "  2. Photograph 100-300 real Bidholi/Kandholi/Pondha potholes and\n"
            "     label them (labelImg / Roboflow / CVAT) in YOLO format.\n"
            "\nStep 2 is not optional for the final demo. RDD2022 has no hill-\n"
            "terrain Uttarakhand data, and a model trained only on it will miss\n"
            "the shaded, gravel-edged damage typical of these roads."
        )


def _remap_rdd(root: Path) -> None:
    """Copies an RDD2022 YOLO export in, collapsing its 4 classes onto our 2."""
    if not root.exists():
        sys.exit(f"RDD2022 path not found: {root}")

    # RDD2022 ships per-country; accept either a country dir or the parent.
    label_dirs = sorted(root.rglob("labels"))
    if not label_dirs:
        sys.exit(
            f"No 'labels' directory under {root}. Convert RDD2022's PASCAL VOC\n"
            "XML annotations to YOLO .txt first (Roboflow does this in one step)."
        )

    # RDD's own class indices, in its canonical order.
    rdd_order = ["D00", "D10", "D20", "D40"]
    kept = dropped = 0

    for label_dir in label_dirs:
        split = "val" if "val" in label_dir.parts else "train"
        image_dir = label_dir.parent / "images"
        if not image_dir.exists():
            continue

        for txt in label_dir.glob("*.txt"):
            out_lines = []
            for line in txt.read_text(encoding="utf-8").splitlines():
                parts = line.split()
                if len(parts) < 5:
                    continue
                try:
                    old_idx = int(parts[0])
                except ValueError:
                    continue
                if old_idx >= len(rdd_order):
                    dropped += 1
                    continue
                target = RDD_MAP.get(rdd_order[old_idx])
                if target is None:
                    dropped += 1
                    continue
                parts[0] = str(CLASSES.index(target))
                out_lines.append(" ".join(parts))
                kept += 1

            # An image whose every box was dropped still has value as a
            # negative example, so copy it across with an empty label file.
            stem = txt.stem
            src_img = next(
                (p for p in image_dir.glob(f"{stem}.*")
                 if p.suffix.lower() in {".jpg", ".jpeg", ".png"}),
                None,
            )
            if src_img is None:
                continue

            shutil.copy2(src_img, DATASET_DIR / "images" / split / src_img.name)
            (DATASET_DIR / "labels" / split / f"{stem}.txt").write_text(
                "\n".join(out_lines), encoding="utf-8"
            )

    print(f"remapped RDD2022: {kept} boxes kept, {dropped} dropped")


# ---------------------------------------------------------------------------
# train
# ---------------------------------------------------------------------------

def cmd_train(args: argparse.Namespace) -> None:
    _require_ultralytics()
    from ultralytics import YOLO

    if not DATA_YAML.exists():
        sys.exit("Run `prepare` first.")

    model = YOLO(args.weights)
    model.train(
        data=str(DATA_YAML),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        project=str(RUNS_DIR),
        name="roadscan",
        exist_ok=True,
        # A phone camera held over a pothole gives one canonical viewpoint, so
        # the useful augmentations are the ones that mimic real capture
        # variation: time of day, shadow, and handheld angle.
        hsv_v=0.4,
        degrees=8.0,
        scale=0.4,
        fliplr=0.5,
        # Potholes have no meaningful vertical symmetry -- flipping them upside
        # down teaches the model nothing it will ever see.
        flipud=0.0,
        patience=25,
    )
    print(f"\nweights: {RUNS_DIR / 'roadscan' / 'weights' / 'best.pt'}")


# ---------------------------------------------------------------------------
# export
# ---------------------------------------------------------------------------

def cmd_export(args: argparse.Namespace) -> None:
    _require_ultralytics()
    from ultralytics import YOLO

    weights = Path(args.weights) if args.weights else (
        RUNS_DIR / "roadscan" / "weights" / "best.pt"
    )
    if not weights.exists():
        sys.exit(f"No weights at {weights}. Train first, or pass --weights.")

    model = YOLO(str(weights))

    # int8 roughly quarters the file and speeds up inference on the CPU
    # delegate, at a small accuracy cost. It needs `data` to calibrate against
    # real images -- without it, the quantisation ranges are guesses and
    # accuracy drops far more than it should.
    exported = model.export(
        format="litert",
        imgsz=args.imgsz,
        int8=args.int8,
        data=str(DATA_YAML) if args.int8 else None,
    )

    src = Path(exported)
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    dst = ASSET_DIR / ASSET_NAME
    shutil.copy2(src, dst)

    size_mb = dst.stat().st_size / (1024 * 1024)
    print(f"exported -> {dst}  ({size_mb:.1f} MB)")
    print("`assets/models/` is already declared in pubspec.yaml, so a rebuild "
          "picks this up automatically.")


# ---------------------------------------------------------------------------
# verify
# ---------------------------------------------------------------------------

def cmd_verify(_: argparse.Namespace) -> None:
    """Checks the bundled export exists and that its class names match what the
    Flutter label matcher expects. Catches the failure mode where a model
    trained with classes like 'D40' silently detects nothing in the app."""
    dst = ASSET_DIR / ASSET_NAME
    if not dst.exists():
        sys.exit(f"missing {dst} -- run `export` first.")
    print(f"found {dst} ({dst.stat().st_size / (1024*1024):.1f} MB)")

    def flutter_maps(name: str) -> str | None:
        s = "".join(ch for ch in name.lower() if ch.isalnum())
        if "pothole" in s or "pot" in s:
            return "pothole"
        if "crack" in s or "crazing" in s or "alligator" in s:
            return "crack"
        return None

    ok = True
    for name in CLASSES:
        mapped = flutter_maps(name)
        status = "OK" if mapped else "UNMAPPED"
        print(f"  {name:10s} -> {mapped or '(dropped by the app)':10s} [{status}]")
        if not mapped:
            ok = False

    if not ok:
        sys.exit(
            "\nAt least one class name will be discarded by the app.\n"
            "Rename it in CLASSES so it contains 'pothole' or 'crack', "
            "retrain, and re-export."
        )
    print("\nclass contract OK")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("prepare", help="create dataset layout + yaml")
    p.add_argument("--rdd2022", help="path to an RDD2022 YOLO export to remap")
    p.set_defaults(func=cmd_prepare)

    p = sub.add_parser("train", help="fine-tune a YOLO nano model")
    p.add_argument("--weights", default="yolo26n.pt")
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--batch", type=int, default=16)
    p.set_defaults(func=cmd_train)

    p = sub.add_parser("export", help="export to LiteRT and copy into assets/")
    p.add_argument("--weights", default=None)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--int8", action="store_true", default=True)
    p.add_argument("--no-int8", dest="int8", action="store_false")
    p.set_defaults(func=cmd_export)

    p = sub.add_parser("verify", help="check the bundled model + class names")
    p.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
